### ISSUE TITLE
Proposed SIG-Content meeting agenda for 2022-01-27

### ISSUE THREAD

**Issue by monroegm** [o3de/sig-content#40] opened 2022-01-26 18:49 UTC
## Meeting Details

- **Date/Time:** January 27, 2021 @ 19:00 UTC / 11:00 AM PT
- **Location:** [Discord SIG-Content Voice Room](https://discord.gg/VV2x4rVn8x)
- **Moderator:** Sempé [AWS] (GitHub: @lsemp3d)
- **Note Taker** TBD

The [SIG-Content Meetings](https://github.com/o3de/sig-content/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

- Sempé [AWS] (GitHub: @lsemp3d) and Gavin Monroe [Amazon] (GitHub: @monroegm) were elected chair and co-chair of SIG-Content

## Meeting Agenda

- Maintainer nominations:
  - #39 
- Open RFCs:
  - #38 
- SIG-Simulation proposal: [o3de/tsc#10 (comment)](https://github.com/o3de/tsc/issues/10#issuecomment-1021128991_)

## Outcomes from Discussion topics

**Discuss outcomes from agenda**

## Action Items

**Create actionable items from proposed topics**

## Open Discussion Items

List any additional items below!

**Comment by hultonha** [comment] 2022-01-26 20:42
### Heads-up/Announcement

We're in discussion with the O3DF TSC about creating a new sig (sig-simulation) which would move several features from sig-core as well as animation from sig-content.

It's been much discussed how both sig-content and sig-core are too large so this spilt is hopefully a step in the right direction. 

We are in very preliminary stages but wanted to make people aware early so any questions/concerns can be voiced.

Please see this issue for more details - https://github.com/o3de/tsc/issues/10#issuecomment-1021128991

**Comment by lsemp3d** [comment] 2022-01-27 19:54
- Discussed and approved reviewer nomination #39 
- Discussed SIG-Simulation proposal, identified that perhaps more information about whether the motivation behind creating a new SIG is the proper mechanism, consider proposing the creation of feature channels instead, the features would still be managed by SIG charter, but communication would be separated by topic/feature, making it easier to find relevant information and follow discussions.
- Discussed #38 it was widely agreed that the proposal is good
- Discussed the matter of inactive pull requests, PRs that have "Change Requests" but do not see any activity from the author
    - Recommended: Creating an issue around the PR and label it as a good-first-issue 
    - Broadcast inactive PRs in the SIG-Content channel for visibility
    - Pin a Good-First-Issue list in the SIG-Content channel 
    - Mechanism to automate the expiry of inactive PRs

**Comment by hultonha** [comment] 2022-01-28 12:45
Thank you for the update @lsemp3d 

Regarding

> Discussed SIG-Simulation proposal, identified that perhaps more information about whether the motivation behind creating a new SIG is the proper mechanism, consider proposing the creation of feature channels instead, the features would still be managed by SIG charter, but communication would be separated by topic/feature, making it easier to find relevant information and follow discussions.

This is something we can definitely discuss with the TSC. With sig-core there is the appetite for splitting and moving physics, cloth, destruction and AI out and moving animation there does seem to make a lot of sense. Would sig-content not be okay with moving animation to a new sig (sig-simulation) if it were created? Would the overhead of sig-core/sig-content communication become a burden? Tagging @greerdv, @SergeyAMZN @moraaar and @amzn-jillich for visibility.

> Discussed Proposed RFC Feature Editor Camera Bookmark System #38 it was widely agreed that the proposal is good

This is great to hear! @AMZN-Igarri will be very pleased 🙂

**Comment by lsemp3d** [comment] 2022-01-28 18:37
> Thank you for the update @lsemp3d
> 
> Regarding
> 
> > Discussed SIG-Simulation proposal, identified that perhaps more information about whether the motivation behind creating a new SIG is the proper mechanism, consider proposing the creation of feature channels instead, the features would still be managed by SIG charter, but communication would be separated by topic/feature, making it easier to find relevant information and follow discussions.
> 
> This is something we can definitely discuss with the TSC. With sig-core there is the appetite for splitting and moving physics, cloth, destruction and AI out and moving animation there does seem to make a lot of sense. Would sig-content not be okay with moving animation to a new sig (sig-simulation) if it were created? Would the overhead of sig-core/sig-content communication become a burden? Tagging @greerdv, @SergeyAMZN @moraaar and @amzn-jillich for visibility.

These were the same sort of questions that came up, we want to identify what problem we are trying to solve and make sure we do it in the best way for everyone. If the issue is about communication, the overhead of an entire SIG may be high, (scheduling new meetings, electing chairs, etc), perhaps having per-feature channels to best filter out conversations is sufficient.

**Comment by hultonha** [comment] 2022-01-31 10:53
I think the main problem we're trying to solve as far as I see it is helping reduce the current workload of both sig-content and sig-core by extracting closely related features that would benefit from having their own dedicated sig.

There is the overhead of additional meetings and the governance side of things, but then with this move more time will be given back to sig-core and sig-content to focus on the areas they own.

I realize it's a big decision, and one not to be taken lightly. We can discuss in the [upcoming TSC meeting](https://github.com/o3de/tsc/issues/11) the idea of aligning cross-sig 'feature streams' to try and help communication and organization. I'm not sure exactly what form this will take though (maybe to start a simulation Discord channel? I'm not sure...).

I'd be interested to hear what other people think. I just don't want us to never consider creating new sigs if they make sense (and also of course potentially merging or closing existing sigs).

Thanks!

**Comment by hultonha** [comment] 2022-03-10 09:42
Closing this issue as the date for this meeting has passed.

**Closed by hultonha** 2022-03-10 09:42 UTC
Labels: mtg-agenda
